# Generated by Django 3.0.3 on 2020-02-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200208_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1581090988.7706077, max_length=20, unique=True),
        ),
    ]
