# Generated by Django 2.1 on 2018-08-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180819_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1534684430.7933502, max_length=20, unique=True),
        ),
    ]
