# Generated by Django 3.0.3 on 2020-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200208_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1581092105.6026473, max_length=20, unique=True),
        ),
    ]
