version: "3"

services:
  db:
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always
    image: postgres:12
    volumes:
      - ./pgdata:/var/lib/postgresql/data:rw
  app:
    environment:
      - DATABASE_URL=${DJANGO_DATABASE_URL}
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_SETTINGS_MODULE=gtszrcp.settings.deploy
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/:rw
      - ./app/logs:/code/logs/:rw
    depends_on:
      - db
