version: "3"

services:
  db:
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always
    image: postgres:12
    ports:
        - 5432:5432
    volumes:
        - ./pgdata.dev:/var/lib/postgresql/data:rw
# app:
#   environment:
#     DATABASE_URL: postgres://ragyeom:ragyeom@db/ragyeom
#     DJANGO_MANAGEPY_MIGRATE: "on"
#   build:
#     context: ./app
#     dockerfile: ./Dockerfile
#   ports:
#     - "8000:8000"
#   volumes:
#     - ./app/uploads:/code/uploads/:rw
#   depends_on:
#     - db
