# Generated by Django 2.1.4 on 2019-11-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_auto_20180606_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, default=None, related_name='artist_as_translator', to='bibliography.Artist'),
        ),
    ]
