# Generated by Django 2.0.5 on 2018-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='slug',
            field=models.SlugField(default=1527345458.615131, max_length=20, unique=True),
        ),
    ]
