# Generated by Django 2.1 on 2018-08-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180606_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1534684363.8143256, max_length=20, unique=True),
        ),
    ]
