# Generated by Django 2.0.5 on 2018-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180527_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527350705.7741303, max_length=20, unique=True),
        ),
    ]
