# Generated by Django 2.1.4 on 2019-11-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180819_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1574507216.7174268, max_length=20, unique=True),
        ),
    ]
