# Generated by Django 2.0.5 on 2018-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180527_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='wirter',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527354940.8105474, max_length=20, unique=True),
        ),
    ]
