# Generated by Django 2.0.5 on 2018-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180527_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527356531.2225487, max_length=20, unique=True),
        ),
    ]
