# Generated by Django 2.0.5 on 2018-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180527_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='createtime',
            new_name='createtimee',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527357676.4592116, max_length=20, unique=True),
        ),
    ]
