# Generated by Django 2.0.5 on 2018-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180527_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='updatetime',
        ),
        migrations.AddField(
            model_name='page',
            name='publisheddate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527402810.581493, max_length=20, unique=True),
        ),
    ]
