# Generated by Django 2.0.5 on 2018-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180527_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='publisheddate',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527403262.8501492, max_length=20, unique=True),
        ),
    ]
