# Generated by Django 2.0.5 on 2018-05-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180527_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527404088.621709, max_length=20, unique=True),
        ),
    ]
