# Generated by Django 2.0.5 on 2018-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180527_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_list',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527404492.229031, max_length=20, unique=True),
        ),
    ]
