# Generated by Django 2.0.5 on 2018-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180527_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527406333.397294, max_length=20, unique=True),
        ),
    ]
