# Generated by Django 2.0.5 on 2018-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20180527_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527406417.5848496, max_length=20, unique=True),
        ),
    ]
