# Generated by Django 2.0.5 on 2018-05-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20180527_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527406596.6066675, max_length=20, unique=True),
        ),
    ]
