# Generated by Django 2.0.5 on 2018-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_auto_20180527_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527421705.7377949, max_length=20, unique=True),
        ),
    ]
