# Generated by Django 2.0.5 on 2018-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180527_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527421997.4524808, max_length=20, unique=True),
        ),
    ]
