# Generated by Django 2.0.5 on 2018-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_auto_20180527_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527433076.917517, max_length=20, unique=True),
        ),
    ]
