# Generated by Django 2.0.5 on 2018-06-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20180603_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527997771.6596322, max_length=20, unique=True),
        ),
    ]
