# Generated by Django 2.0.5 on 2018-06-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20180603_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527998288.338286, max_length=20, unique=True),
        ),
    ]
