# Generated by Django 2.0.5 on 2018-06-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20180603_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527999001.5035927, max_length=20, unique=True),
        ),
    ]
