# Generated by Django 2.0.5 on 2018-06-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20180603_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1527999438.5902498, max_length=20, unique=True),
        ),
    ]
