# Generated by Django 2.0.5 on 2018-06-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20180603_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1528000015.0255353, max_length=20, unique=True),
        ),
    ]
