# Generated by Django 2.0.5 on 2018-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20180603_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1528000058.8355982, max_length=20, unique=True),
        ),
    ]
