# Generated by Django 2.0.5 on 2018-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180603_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1528031698.2609496, max_length=20, unique=True),
        ),
    ]
