# Generated by Django 2.0.5 on 2018-06-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20180527_1636'),
        ('pages', '0035_auto_20180603_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photo.Gallery'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1528211474.4448667, max_length=20, unique=True),
        ),
    ]
