# Generated by Django 2.0.5 on 2018-06-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20180606_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1528221380.3078463, max_length=20, unique=True),
        ),
    ]
