# Generated by Django 2.0.5 on 2018-06-03 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photo', '0002_auto_20180527_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('language', models.CharField(max_length=100)),
                ('publisher_place', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('page_amt', models.IntegerField(default=1, null=True)),
                ('binding_type', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_date', models.DateField()),
                ('colorspace', models.CharField(choices=[('CMYK', 'CMYK'), ('RGB', 'RGB'), ('GRAY', 'Grayscale'), ('BNW', 'Black And White')], max_length=100)),
                ('price', models.FloatField(default=1, null=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('summary', models.TextField()),
                ('figs', models.TextField(blank=True, null=True)),
                ('toc', models.TextField(null=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ManyToManyField(blank=True, related_name='artist_as_designer', to='bibliography.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Bookshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_eng', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='distributor',
            field=models.ManyToManyField(blank=True, related_name='publisher_as_distributor', to='bibliography.Bookshop'),
        ),
        migrations.AddField(
            model_name='book',
            name='editor',
            field=models.ManyToManyField(blank=True, related_name='artist_as_editor', to='bibliography.Artist'),
        ),
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='photo.Gallery'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='bibliography.Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(blank=True, related_name='artist_as_writer', to='bibliography.Artist'),
        ),
    ]
