# Generated by Django 2.0.5 on 2018-05-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('written_in', models.CharField(max_length=100)),
                ('publisher_place', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('page_amt', models.IntegerField(default=1)),
                ('binding_type', models.CharField(max_length=100)),
                ('colorspace', models.CharField(choices=[('CMYK', 'CMYK'), ('RGB', 'RGB'), ('GRAY', 'Grayscale'), ('BNW', 'Black And White')], max_length=100)),
                ('price', models.FloatField(default=1)),
                ('summary', models.TextField()),
                ('toc', models.TextField()),
                ('publishedtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('designer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist_as_designer', to='bibliography.Artists')),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Publishers'),
        ),
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist_as_writer', to='bibliography.Artists'),
        ),
    ]
