# Generated by Django 2.0.5 on 2018-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='designer',
            field=models.ManyToManyField(blank=True, default=2, related_name='artist_as_designer', to='bibliography.Artist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default='Korean', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(default=1, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_place',
            field=models.CharField(default='Seoul', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='toc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ManyToManyField(blank=True, default=1, related_name='artist_as_writer', to='bibliography.Artist'),
        ),
        migrations.AlterField(
            model_name='bookshop',
            name='country',
            field=models.CharField(blank=True, default='Korea', max_length=50, null=True),
        ),
    ]
