# Generated by Django 2.0.5 on 2018-06-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='images',
        ),
    ]
