# Generated by Django 2.0.5 on 2018-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0002_auto_20180525_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527261211.4067574, max_length=20, unique=True),
        ),
    ]
