# Generated by Django 2.0.5 on 2018-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0003_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='distributor',
            field=models.ManyToManyField(null=True, related_name='publisher_as_distributor', to='bibliography.Bookshop'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527261465.5573559, max_length=20, unique=True),
        ),
    ]
