# Generated by Django 2.0.5 on 2018-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0004_auto_20180526_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='written_in',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527269566.049808, max_length=20, unique=True),
        ),
    ]
