# Generated by Django 2.0.5 on 2018-05-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_auto_20180526_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist_as_designer', to='bibliography.Artist'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bibliography.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527321374.3519945, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='artist_as_writer', to='bibliography.Artist'),
        ),
    ]
