# Generated by Django 2.0.5 on 2018-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_auto_20180526_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='distributor',
            field=models.ManyToManyField(blank=True, null=True, related_name='publisher_as_distributor', to='bibliography.Bookshop'),
        ),
        migrations.AlterField(
            model_name='book',
            name='figs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_amt',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527321529.624852, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='toc',
            field=models.TextField(null=True),
        ),
    ]
