# Generated by Django 2.0.5 on 2018-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0008_auto_20180526_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527345437.4849682, max_length=20, unique=True),
        ),
    ]
