# Generated by Django 2.0.5 on 2018-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0009_auto_20180526_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='distributor',
            field=models.ManyToManyField(blank=True, related_name='publisher_as_distributor', to='bibliography.Bookshop'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527345458.5995052, max_length=20, unique=True),
        ),
    ]
