# Generated by Django 2.0.5 on 2018-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0011_auto_20180527_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527350705.7585058, max_length=20, unique=True),
        ),
    ]
