# Generated by Django 2.0.5 on 2018-05-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0013_auto_20180527_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527354940.8055515, max_length=20, unique=True),
        ),
    ]
