# Generated by Django 2.0.5 on 2018-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0014_auto_20180527_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527356531.217552, max_length=20, unique=True),
        ),
    ]
