# Generated by Django 2.0.5 on 2018-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0017_auto_20180527_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527402810.5774953, max_length=20, unique=True),
        ),
    ]
