# Generated by Django 2.0.5 on 2018-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0019_auto_20180527_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527403262.8451521, max_length=20, unique=True),
        ),
    ]
