# Generated by Django 2.0.5 on 2018-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0020_auto_20180527_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527403378.816309, max_length=20, unique=True),
        ),
    ]
