# Generated by Django 2.0.5 on 2018-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0022_auto_20180527_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishedtime',
            new_name='pub_time',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527404103.842091, max_length=20, unique=True),
        ),
    ]
