# Generated by Django 2.0.5 on 2018-05-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0023_auto_20180527_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527404144.8474455, max_length=20, unique=True),
        ),
    ]
