# Generated by Django 2.0.5 on 2018-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0024_auto_20180527_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_time',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527404246.88032, max_length=20, unique=True),
        ),
    ]
