# Generated by Django 2.0.5 on 2018-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0025_auto_20180527_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1527404492.2250333, max_length=20, unique=True),
        ),
    ]
