# Generated by Django 2.0.5 on 2018-05-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0026_auto_20180527_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
