# Generated by Django 2.0.5 on 2018-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0027_auto_20180527_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
