# Generated by Django 3.0.3 on 2020-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1581090143.878701, max_length=20, unique=True),
        ),
    ]
