# Generated by Django 3.0.3 on 2020-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200208_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1581092272.896395, max_length=20, unique=True),
        ),
    ]
