# Generated by Django 3.0.3 on 2020-02-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200208_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(default=1581131990.0307555, max_length=20, unique=True),
        ),
    ]
