version: "3"

services:
  db:
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always
    image: postgres:12
    ports:
        - 5431:5432
    volumes:
        - ./pgdata.dev:/var/lib/postgresql/data:rw
